### ISSUE TITLE
Datawatcher crash :0

### ISSUE THREAD

**Issue by brandyyn** [makamys/DMod#9]
[crash-2023-09-06_11.09.22-client.txt](https://github.com/makamys/DMod/files/12536193/crash-2023-09-06_11.09.22-client.txt)

[latest.log](https://github.com/makamys/DMod/files/12536196/latest.log)

**Comment by brandyyn** [comment]
[crash-2023-11-14_07.47.06-client.txt](https://github.com/makamys/DMod/files/13345920/crash-2023-11-14_07.47.06-client.txt)

[latest.log](https://github.com/makamys/DMod/files/13345921/latest.log)

@makamys

**Comment by makamys** [comment]
This looks like a datawatcher ID conflict. Foxes use IDs 18-22, I'm guessing some other mod also uses ID 18. You could try searching in your configs. Maybe I should make the IDs used by my mod configurable as well.

I found a mod that may help you find the conflict: ID Conflicts Viewer ([Modrinth](https://modrinth.com/mod/idcv/versions) | [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/idcv))

~~If it's not that then it might be an EndlessIDs issue, it extends data watcher IDs which can be disabled in its config.~~ Nvm, you have DataWatcher extension disabled already.

**Comment by brandyyn** [comment]
> This looks like a datawatcher ID conflict. Foxes use IDs 18-22, I'm guessing some other mod also uses ID 18. You could try searching in your configs. Maybe I should make the IDs used by my mod configurable as well.
> 
> I found a mod that may help you find the conflict: ID Conflicts Viewer ([Modrinth](https://modrinth.com/mod/idcv/versions) | [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/idcv))
> 
> ~If it's not that then it might be an EndlessIDs issue, it extends data watcher IDs which can be disabled in its config.~ Nvm, you have DataWatcher extension disabled already.

it would be good to have the datawatcher customizable if you could do that for me :)

**Comment by makamys** [comment]
I realized that IDCV won't actually help with this, because it only detects the same conflicts vanilla warns about. I added a CoreTweaks feature that will warn about the ones they don't ([get the build here](https://github.com/makamys/CoreTweaks/suites/18200620608/artifacts/1050718300)). You'll have to enable `detectDataWatcherIdConflictCulprit` in the config to get the most information. Let me know if you can get a log with it.

**Comment by brandyyn** [comment]
> I realized that IDCV won't actually help with this, because it only detects the same conflicts vanilla warns about. I added a CoreTweaks feature that will warn about the ones they don't ([get the build here](https://github.com/makamys/CoreTweaks/suites/18200620608/artifacts/1050718300)). You'll have to enable `detectDataWatcherIdConflictCulprit` in the config to get the most information. Let me know if you can get a log with it.

just had the chance to check, i couldnt find anything in my logs relating to datawatchers or coretweaks after enabling the config option although im pretty sure this config option (or maybe it was just the new version of coretweaks) had messed up my game? i created a new world and instead of getting my starting items i got a bunch of random items and world generation was messed up, modded trees were made out of different blocks in the mod than usual and there was constant lightning even though it's sunny?

**Comment by makamys** [comment]
The option only adds prints, it doesn't change any behavior, so it couldn't have been it. You could try disabling all CoreTweaks features other than that option for now. (You can most easily do this by doing search and replaces for `S:_enabled=true` and `S:_enabled=force`, replacing them with `S:_enabled=false`, then enabling just that option.)

**Comment by brandyyn** [comment]
you're right, not sure, must have been some unrelated issue. really weird because i have never seen it before

anywany, i finally got a chance to test it with the config option on- here's me crashing on world creation with the same crash and the config options enabled: 

[latest.log](https://github.com/makamys/DMod/files/13412919/latest.log)

[crash-2023-11-20_10.38.35-client.txt](https://github.com/makamys/DMod/files/13412927/crash-2023-11-20_10.38.35-client.txt)

what about the addition of the ability to change the datawatcher in d-mod?

also this doesnt happen from spawning foxes manually with a spawn egg, thought that was important to note

**Comment by makamys** [comment]
You seem to have attached the wrong log file, there's barely anything in it, unlike the previous one that was 105 KB. `fml-client-latest.log` is the one you want to grab with MultiMC-based launchers like PolyMC.

I *could* add an option to change DataWatcher IDs, but I would like to fully understand the issue first, since there might be a better solution, and also to reduce the amount of trial and error needed on your part to fix it.

**Comment by brandyyn** [comment]
sorry for the delay, i have been extremely busy with university but here's a new log for you:

[crash-2023-11-27_14.50.59-client.txt](https://github.com/makamys/DMod/files/13476594/crash-2023-11-27_14.50.59-client.txt)

[fml-client-latest.log](https://github.com/makamys/DMod/files/13476595/fml-client-latest.log)


> You seem to have attached the wrong log file, there's barely anything in it, unlike the previous one that was 105 KB. fml-client-latest.log is the one you want to grab with MultiMC-based launchers like PolyMC.

i had changed launchers so i totally forgot, sorry !

**Comment by brandyyn** [comment]
those last ones were on world creation and this one is after world creation (new world) and flying around for a few seconds- 

[crash-2023-11-27_18.20.06-client.txt](https://github.com/makamys/DMod/files/13478811/crash-2023-11-27_18.20.06-client.txt)

[fml-client-latest.log](https://github.com/makamys/DMod/files/13478812/fml-client-latest.log)

**Comment by makamys** [comment]
Well, I'm stumped. The logs don't indicate any ID conflicts, so I have no idea why else it could be breaking. I pushed a branch that adds configs for the IDs (you can get the build [here](https://github.com/makamys/DMod/suites/18536562815/artifacts/1076182008)), but I'm not sure if changing them will fix anything.

**Comment by brandyyn** [comment]
> Well, I'm stumped. The logs don't indicate any ID conflicts, so I have no idea why else it could be breaking. I pushed a branch that adds configs for the IDs (you can get the build [here](https://github.com/makamys/DMod/suites/18536562815/artifacts/1076182008)), but I'm not sure if changing them will fix anything.

it LOOKS LIKE changing the owner value id value fixed it? I changed them all but I still crashed the first time when I missed the owner id, but after changing it I haven't had any crashes YET. Will report back if I get any.
